### ISSUE TITLE
where is the pack?

### ISSUE THREAD

**Issue by x-75** [Wurnace/sfs-lasers#1]
i think you forgot to put the file in the releases

**Comment by guunno** [comment]
![image](https://github.com/Wurnace/sfs-lasers/assets/122387227/78a7480c-cace-44d6-b4e4-086e9f746c4f)
Hi, if you press the "Code" button, and press "Download ZIP" where it is shown in the image above, then you can download the pack. All you need to do is unzip it and move it into the appropriate folder. I hope this solves your problem :)

**Comment by guunno** [comment]
However, I will make a release for an easier way of installing the pack in the next version.

**Comment by x-75** [comment]
ok thanks for the help
